version: '3.7'
services:
  api-nginx:
    build:
      context: ./api/docker
      dockerfile: dev/nginx/Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "8080:80"
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: ./api/docker
      dockerfile: dev/php-fpm/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-postgres

  api-php-cli:
    build:
      context: ./api/docker
      dockerfile: dev/php-cli/Dockerfile
    volumes:
      - ./api:/app
      - composer:/root/.composer/cache
    depends_on:
      - api-postgres
    working_dir: /app
    tty: true

  api-postgres:
    image: postgres:11.2-alpine
    volumes:
      - api-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"


  frontend-nginx:
    build:
      context: ./frontend/docker
      dockerfile: dev/nginx/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8081:80"
    depends_on:
      - api-php-fpm

volumes:
  composer:
  api-postgres:
