doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '11.2'
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
        types:
            user_user_id: 'Infrastructure\Doctrine\Types\User\IdType'
            user_user_login: 'Infrastructure\Doctrine\Types\User\LoginType'
            user_user_email: 'Infrastructure\Doctrine\Types\User\EmailType'
            user_user_age: 'Infrastructure\Doctrine\Types\User\AgeType'
            user_user_password: 'Infrastructure\Doctrine\Types\User\PasswordType'
            user_user_status: 'Infrastructure\Doctrine\Types\User\StatusType'
            user_user_role: 'Infrastructure\Doctrine\Types\User\RoleType'
            music_artist_id: 'Infrastructure\Doctrine\Types\Music\Artist\IdType'
            music_artist_login: 'Infrastructure\Doctrine\Types\Music\Artist\LoginType'
        default_table_options:
            charset: utf8
            collate: -

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Model/User'
                prefix: 'Domain\Model\User'
                alias: User

            Music:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Model/Music'
                prefix: 'Domain\Model\Music'
                alias: Music
