security:
  providers:
    fetcher:
      id: Api\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api_token:
      pattern: ^/token$
      security: false

    api:
      pattern: ^/api
      anonymous: true
      stateless: true
      oauth2: true

  access_control:
    - { path: ^/api/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/sign-up, roles: IS_AUTHENTICATED_ANONYMOUSLY }