parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Http\:
        resource: '../src/Http'

    Infrastructure\:
        resource: '../src/Infrastructure'

    Domain\:
        resource: '../src/Domain'

    Api\:
        resource: '../src/Api'

    Console\:
        resource: '../src/Console'

    Api\Action\:
        resource: '../src/Api/Action/'
        tags: ['controller.service_arguments']

    Http\Response\ResponseFactory:
        class: Infrastructure\Http\Response\SymfonyHttpResponseFactory

    Test\Functional\:
        resource: '../tests/Functional/**/*Fixture.php'
        tags: [ 'doctrine.fixture.orm' ]

    Api\ReadModel\UserFetcher:
        class: Infrastructure\ReadModel\DoctrineUserFetcher

    ## Domain

    Domain\Model\Flusher:
        class: Infrastructure\Domain\Model\DoctrineFlusher

    ### Service

    Domain\Model\User\Service\PasswordHasher:
        class: Infrastructure\Domain\Model\User\Service\Argon2idPasswordHasher

    Domain\Model\User\Service\PasswordValidator:
        class: Infrastructure\Domain\Model\User\Service\CorePasswordValidator

    Domain\Model\User\Service\Tokenizer:
        class: Infrastructure\Domain\Model\User\Service\UuidTokenGenerator
        arguments: ['PT1H']

    ### Repository

    Domain\Model\User\UserRepository:
        class: Infrastructure\Domain\Model\User\DoctrineUserRepository

    Domain\Model\Music\Artist\ArtistRepository:
        class: Infrastructure\Domain\Model\Music\DoctrineArtistRepository

